# Generated by Django 6.0.5 on 2026-05-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
